global:
  scrape_interval: 5s

scrape_configs:
  - job_name: participant-a
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway-a:8000"]
        labels: { participant: "A" }

  - job_name: participant-b
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway-b:8000"]
        labels: { participant: "B" }
